### ISSUE TITLE
Workshop preparations

### ISSUE THREAD

**Issue by miykael** [miykael/workshop_pybrain#6]
Hi @peerherholz, I thought I create a new issue to sketch out what still needs to be done.

The docker environment should be stable and probably stays as is. I've fixed nistats, pybids and some other packages to specific versions and made sure that all test pass.

The following things still need to be done:

- [x] Update and writing of intro slides `day1_01_intro.html` to include remoteness, Cambridge, sli.do and perhaps a quick photo of us two
- [x] Slides need to be verified and potentially updated to the new time restrictions
- [x] Links to notebooks from within slides need to be updated to new names
- [x] Not sure if you want to update some figures/flow-charts of the [machine learning intro notebook](https://github.com/miykael/workshop_pybrain/blob/master/notebooks/03b_Predicting_age_with_machine_learning.ipynb)
- [x] Content for `nimare` and `brainspace`: Either as notebooks or addition to innovation slides
- [x] I need to create a notebook for the "Creation of a Nipype Pipeline" part. I want to use something else as the handson from `nipype_tutorial`. Just to have a bit everything in one pipeline: Nipype, Nilearn, Atlasreader (and perhaps nistats?)
- [x] I kept the Machine Learning preparation notebook, to quickly explain the dataset, used for the [MVPA notebook](https://github.com/miykael/workshop_pybrain/blob/master/notebooks/05b_machine_learning_nilearn.ipynb).
- [x] Deep Learning notebook is not yet written. Needs to be explored if this is possible and if we should use the Eye open/closed dataset or the one from the first connectivity analysis. (or both?)
- [x] Some of the outputs in the [PyBIDS](https://github.com/miykael/workshop_pybrain/blob/master/notebooks/04a_pybids.ipynb) notebook lead to `[]` empty cells. I'm not sure if this is intended or not. Please verify that this and the nistats notebooks look good to you.

**Comment by PeerHerholz** [comment]
- [x] update `nistats` to reflect new changes/updates in `nilearn` release, see [here](https://6228-1235740-gh.circle-artifacts.com/0/doc/_build/html/auto_examples/index.html#glm-first-level-analysis-examples), [here](https://6228-1235740-gh.circle-artifacts.com/0/doc/_build/html/auto_examples/index.html#glm-second-level-analysis-examples) and [here](https://6228-1235740-gh.circle-artifacts.com/0/doc/_build/html/auto_examples/07_advanced/plot_bids_analysis.html#sphx-glr-auto-examples-07-advanced-plot-bids-analysis-py)

**Comment by miykael** [comment]
The two things still open are:
- [x] Not sure if you want to update some figures/flow-charts of the [machine learning intro notebook](https://github.com/miykael/workshop_pybrain/blob/master/notebooks/03b_Predicting_age_with_machine_learning.ipynb)
- [x] Content for `nimare` and `brainspace`: Either as notebooks or addition to innovation slides

All good to be closed?

**Comment by PeerHerholz** [comment]
Re the `machine learning notebook`: I'm not sure what you're referring to, do you perhaps have examples?
Re `nimare` and `brainspace`: I added them within the `python module` section of the `innovation slides`

**Comment by miykael** [comment]
The first comment was just with respect to a few of the flow charts (like [this one](https://github.com/miykael/workshop_pybrain/blob/master/workshop/notebooks/data/KCV.png)) in [this notebook](https://nbviewer.jupyter.org/github/miykael/workshop_pybrain/blob/master/workshop/notebooks/03b_predicting_age_with_machine_learning.ipynb).

**Comment by miykael** [comment]
Given that everything is addressed, I will go forward and close this issue.
